"""initial schema: users, patients, radiomics_features

Revision ID: 3d11a3cca4c2
Revises: 
Create Date: 2026-06-22 11:34:07.824725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d11a3cca4c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('classification_cancer', sa.Integer(), nullable=True),
    sa.Column('surgical_cancer', sa.String(length=10), nullable=True),
    sa.Column('surgical_cancer_t', sa.String(length=10), nullable=True),
    sa.Column('surgical_cancer_n', sa.String(length=10), nullable=True),
    sa.Column('surgical_cancer_m', sa.String(length=10), nullable=True),
    sa.Column('boundary_surgical', sa.Integer(), nullable=True),
    sa.Column('involmentrenal', sa.Boolean(), nullable=True),
    sa.Column('lymphrenal', sa.Boolean(), nullable=True),
    sa.Column('surgicalmethod', sa.Text(), nullable=True),
    sa.Column('antidrug', sa.Text(), nullable=True),
    sa.Column('totaldose', sa.Integer(), nullable=True),
    sa.Column('radiationcnt', sa.Integer(), nullable=True),
    sa.Column('radiationperdose', sa.Float(), nullable=True),
    sa.Column('treatmethod', sa.Integer(), nullable=True),
    sa.Column('treatech', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.String(length=6), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('bp', sa.String(length=1), nullable=True),
    sa.Column('bs', sa.String(length=1), nullable=True),
    sa.Column('sm', sa.String(length=1), nullable=True),
    sa.Column('familyhistory', sa.String(length=1), nullable=True),
    sa.Column('locationcancer', sa.Integer(), nullable=True),
    sa.Column('cancerimaging', sa.String(length=10), nullable=True),
    sa.Column('cancerimaging_t', sa.String(length=10), nullable=True),
    sa.Column('cancerimaging_n', sa.String(length=10), nullable=True),
    sa.Column('cancerimaging_m', sa.String(length=10), nullable=True),
    sa.Column('initialdate', sa.Date(), nullable=True),
    sa.Column('treatedate', sa.Date(), nullable=True),
    sa.Column('relapse', sa.Integer(), nullable=True),
    sa.Column('relapsedate', sa.Date(), nullable=True),
    sa.Column('dead', sa.Integer(), nullable=True),
    sa.Column('deathdate', sa.Date(), nullable=True),
    sa.Column('deathsign', sa.Integer(), nullable=True),
    sa.Column('lastdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('radiomics_features',
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'source', 'version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radiomics_features')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
